// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SmartOrganizer.Timetable.DataAccess;
using System;

namespace SmartOrganizer.Timetable.API.Migrations
{
	[DbContext(typeof(TimetableContext))]
	partial class TimetableContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "2.0.1-rtm-125")
				.HasAnnotation("Relational:Sequence:.appointment_hilo", "'appointment_hilo', '', '1', '10', '', '', 'Int64', 'False'")
				.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("SmartOrganizer.Timetable.API.Models.Appointment", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasAnnotation("SqlServer:HiLoSequenceName", "appointment_hilo")
						.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

					b.Property<DateTime>("CreationDate");

					b.Property<string>("Description")
						.HasMaxLength(1000);

					b.Property<DateTime>("EndDate");

					b.Property<string>("Location");

					b.Property<DateTime>("StartDate");

					b.Property<string>("Title")
						.HasMaxLength(100);

					b.HasKey("Id");

					b.ToTable("Appointment");
				});
#pragma warning restore 612, 618
		}
	}
}
